spring:
  servlet:
    multipart:
      max-file-size: 40MB
      max-request-size: 40MB

file:
  path:
    upload: "D:/test/uploads"

excel:
  template:
    config:
      1:
        displayGrid: false
        sheetName: "Sheet1"
        rowPosition: 1
        columnPosition: 0
        headers:
          - Id
          - Name
          - Subject1
          - Subject2
          - Subject3
          - Subject4
          - Subject5
          - Subject6
          - Subject7
          - Subject8